### PR TITLE
Fix/get evidence

### LINKED ISSUE #251: Dispute Details should distinguish between complainant evidence and respondant evidence
Currently the dispute details only returns a raw array of evidence. It would be nice to be able to distinguish (from the API perspective) who submitted what evidence.
- [ ] API contracts
- [ ] Services Implementation
- [ ] Frontend Integration

### LINKED ISSUE #252: Integration of dispute experts with database
The `/dispute/:id` endpoint returns stubbed experts. This should be changed so it queries the appropriate experts assigned to the dispute.

https://github.com/COS301-SE-2024/Dispute-Resolution-Engine/blob/e29992718cff366abb45e063fce8145f1b69597f/api/handlers/dispute.go#L233-L255

### PR DESCRIPTION
**Pull request by CaelanHill**

### CODE REVIEW

File: api/handlers/dispute.go [hunk 1]
```diff
@@ -223,37 +231,69 @@ func (h Dispute) getDispute(c *gin.Context) {
...
+		JOIN 
+			files f ON de.file_id = f.id
+		JOIN 
+			disputes d ON de.dispute = d.id
+		WHERE 
+			de.dispute = ?
+	`
+
+	var evidence []models.Evidence
+	err = h.DB.Raw(evidenceQuery, id).Scan(&evidence).Error
```
Comment (ghost) [inline api/handlers/dispute.go]: why you rawdogging the query? What's wrong with using functions like `Select`, `Joins` and `WHERE`?

File: api/handlers/dispute.go [hunk 2]
```diff
@@ -223,37 +231,69 @@ func (h Dispute) getDispute(c *gin.Context) {
...
+			u.phone_number AS phone,
+			u.role
+		FROM 
+			dispute_experts de, users u
+		WHERE 
+			de.dispute = ? 
+			AND de.user = u.id
+			AND de.status = 'Approved'
+			AND (u.role = 'Mediator' OR u.role = 'Arbitrator' OR u.role = 'Conciliator')
+	`
```
Comment (ghost) [inline api/handlers/dispute.go]: More raw SWL >:(

**Review by ghost — APPROVED** [review]
happy happy
